Run Data Analysis
=================
Anil Satram

25 September 2015


Pre-requisite
-------------
#Load required pacakges:

```{r}
packages <- c("data.table", "reshape2","knitr")
sapply(packages, require, character.only=TRUE, quietly=TRUE)
```

Recognise Path and list files
```{r}
path <- getwd()
filespath <- file.path(path, "UCI HAR Dataset")
list.files(filespath, recursive=TRUE)
```

Read Train and Test Data into R
```{r}
trainSubData <- data.table(read.table(file.path(filespath, "train", "subject_train.txt")))
testSubData  <- data.table(read.table(file.path(filespath, "test" , "subject_test.txt" )))
```

Read Train and Test Activity Data into R
```{r}
lableTrainActData <- data.table(read.table(file.path(filespath, "train", "Y_train.txt")))
labelTestActData  <- data.table(read.table(file.path(filespath, "test" , "Y_test.txt" )))
setTrainActData <- data.table(read.table(file.path(filespath, "train", "X_train.txt")))
setTestActData  <- data.table(read.table(file.path(filespath, "test" , "X_test.txt" )))

```



1 - Merges the training and the test sets to create one data set.
-------------------------------------------------------------

```{r}
sDat <- rbind(trainSubData, testSubData)
setnames(sDat, "V1", "subject")

aDat <- rbind(lableTrainActData, labelTestActData)
setnames(aDat, "V1", "activityNum")
dt <- rbind(setTrainActData, setTestActData)

subdt <- cbind(sDat, aDat)
dt <- cbind(subdt, dt)
setkey(dt, subject, activityNum)
head(dt, n=3)
```

2 - Extracts only the measurements on the mean and standard deviation for each measurement.
---------------------------------------------------------------------------------------

```{r}
dtFeatures <- data.table(read.table(file.path(filespath, "features.txt")))
setnames(dtFeatures, names(dtFeatures), c("featureNum", "featureName"))

dtFeatures <- dtFeatures[grepl("mean\\(\\)|std\\(\\)", featureName)]
dtFeatures$featureCode <- dtFeatures[, paste0("V", featureNum)]
head(dtFeatures)
dtFeatures$featureCode
select <- c(key(dt), dtFeatures$featureCode)
dt <- dt[, select, with=FALSE]
```

3 - Uses descriptive activity names to name the activities in the data set
---------------------------------------------------------------------------

```{r}
dtActNames <- data.table(read.table(file.path(filespath,"activity_labels.txt")))
setnames(dtActNames, names(dtActNames), c("activityNum", "activityName"))
```
4 - Appropriately labels the data set with descriptive variable names.
-----------------------------------------------------------------------

```{r}
dt <- merge(dt, dtActNames, by="activityNum", all.x=TRUE)
setkey(dt, subject, activityNum, activityName)
dt <- data.table(melt(dt, key(dt), variable.name="featureCode"))
dt$activity <- factor(dt$activityName)
dt <- merge(dt, dtFeatures[, list(featureNum, featureCode, featureName)], by="featureCode", all.x=TRUE)
#dt$feature <- factor(dt$featureName)
dt$activity <- factor(dt$activityName)
dt$feature <- factor(dt$featureName)
```

Features with 1 category
```{r}
dt$featJerk <- factor(grepl("Jerk", dt$feature), labels=c(NA, "Jerk"))
dt$featMagnitude <- factor(grepl("Mag", dt$feature), labels=c(NA, "Magnitude"))
```

Features with 2 categories
```{r}
Y <- matrix(seq(1,2), nrow=2)
X <- matrix(c(grepl("^t", dt$feature), grepl("^f", dt$feature)), ncol=nrow(Y))
dt$featDomain <- factor(X %*% Y, labels=c("Time", "Freq"))

X <- matrix(c(grepl("Acc", dt$feature), grepl("Gyro", dt$feature)), ncol=nrow(Y))
dt$featInstrument <- factor(X %*% Y, labels=c("Accelerometer", "Gyroscope"))


X <- matrix(c(grepl("BodyAcc", dt$feature), grepl("GravityAcc", dt$feature)), ncol=nrow(Y))
dt$featAcceleration <- factor(X %*% Y, labels=c(NA, "Body", "Gravity"))


X <- matrix(c(grepl("mean()", dt$feature), grepl("std()", dt$feature)), ncol=nrow(Y))
dt$featVariable <- factor(X %*% Y, labels=c("Mean", "SD"))
```


Features with 3 categories
```{r}
Y <- matrix(seq(1,3), nrow=3)
X <- matrix(c(grepl("-X", dt$feature), grepl("-Y", dt$feature), grepl("-Z", dt$feature)), ncol=nrow(Y))
dt$featAxis <- factor(X %*% Y, labels=c(NA, "X", "Y", "Z"))

r1 <- nrow(dt[, .N, by=c("feature")])
r2 <- nrow(dt[, .N, by=c("featDomain", "featAcceleration", "featInstrument", "featJerk", "featMagnitude", "featVariable", "featAxis")])
r1 == r2

setkey(dt, subject, activity, featDomain, featAcceleration, featInstrument, featJerk, featMagnitude, featVariable, featAxis)
tidyData<- dt[, list(count = .N, average = mean(value)), by=key(dt)]
```
Generate Codebook
-------------------
```{r}
knit("codebook.Rmd", encoding="ISO8859-1")
```




